In [1]:
import tensorflow as tf

 #Initialize two constants
x1 = tf.constant([1,2,3,4])
x2 = tf.constant([5,6,7,8])

 #Multiply constants
result = tf.multiply(x1,x2)

print(result)

tf.Tensor([ 5 12 21 32], shape=(4,), dtype=int32)


In [11]:
import tensorflow as tf

tf.compat.v1.disable_eager_execution() #
#Initialize two constants
x1 = tf.constant([1,2,3,4])
x2 = tf.constant([5,6,7,8])

#Multiply constants
result = x1*x2

#Initialize interactive session
sess = tf.compat.v1.Session()

#Print the result in the session
print(sess.run(result))

#Close the session
sess.close()

[ 5 12 21 32]


In [12]:
sess

In [14]:
import tensorflow as tf

#Initialize two constants
x1 = tf.constant([1,2,3,4])
x2 = tf. constant([5,6,7,8])

#Multiply
new_new_result = tf.multiply(x1,x2)

#Initialize Session and run 'result'
with tf.compat.v1.Session() as sess:
  output = sess.run(new_new_result)
  print(output)

[ 5 12 21 32]


In [6]:
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.7/dist-packages/tensorflow/_api/v2/version/__init__.py'>


In [7]:
print(tf.__version__)

2.5.0
